name = "nav-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "NAV_DB"
database_name = "book"
database_id = "local-dev-db"

[[kv_namespaces]]
binding = "NAV_AUTH"
id = "local-dev-kv"
